// src/popup/App.vue
<template>
  <div>
    <!-- Main user interface -->
    <popup-user-settings/>

    <!-- Modal on Success -->
    <done-modal/>

    <!-- Modal on not supported language -->
    <change-language-modal/>

    <!-- Modal on no token detected -->
    <no-token-detected-modal/>
  </div>
</template>

<script lang="ts">

import { Subject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';
import Vue from 'vue';
import Component from 'vue-class-component';
import ChangeLanguageModal from '../components/change-language.modal.vue';
import DoneModal from '../components/done.modal.vue';
import NoTokenDetectedModal from '../components/no-token-detected.modal.vue';
import PopupUserSettings from '../components/popup.user-settings.vue';
import { ACTION } from '../constants';
import {
  StatusReportAction,
  UpdateBadgeAction,
} from '../libs/events/actions';
import {
  listenTo,
  sendMessage,
} from '../libs/events/events';
import { storeLastBadgeClicked } from '../libs/storage/chrome.storage';

@Component({
  components: {
    DoneModal,
    NoTokenDetectedModal,
    ChangeLanguageModal,
    PopupUserSettings,
  },
})
export default class App extends Vue {
  public status = 'USER_SETTINGS';
  onDestroy$: Subject<boolean> = new Subject();

  destroyed() {
    this.onDestroy$.next(true);
    this.onDestroy$.complete();
  }

  showModal(status: string) {
    this.$root.$emit('bv::show::modal', status);
  }


  mounted() {
    // Store Badge is clicked now and send event later
    storeLastBadgeClicked()
      .subscribe(() => sendMessage(new UpdateBadgeAction()));

    // Listen to Show modal event on status report
    listenTo<StatusReportAction>(ACTION.STATUS_REPORT)
      .pipe(
        takeUntil(this.onDestroy$),
      )
      .subscribe(({action}) => {
        this.status = action.status;
        this.showModal(action.status);
      });
  }
}
</script>

<style lang="scss">

</style>

// src/popup/App.tsx
import React from 'react';
import { Subject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';
import ChangeLanguageModal from '../components/modals/change-language.modal';
import DoneModal from '../components/modals/done.modal';
import NoTokenDetectedModal from '../components/modals/no-token-detected.modal';
import UserSettings from '../components/user-settings/user-settings';
import { ACTION } from '../constants';
import {
  StatusReportAction,
  UpdateBadgeAction,
} from '../libs/events/actions';
import {
  listenTo,
  sendMessage,
} from '../libs/events/events';
import { storeLastBadgeClicked } from '../libs/storage/chrome.storage';
import './App.scss';

interface AppState {
  modal?: string
}

export default class App extends React.Component<any, AppState> {
  onDestroy$: Subject<boolean> = new Subject();

  constructor(params: any) {
    super(params);
    this.state = {
      modal: null,
    };
  }

  componentWillUnmount() {
    this.onDestroy$.next(true);
    this.onDestroy$.complete();
  }

  componentDidMount() {
    // Store Badge is clicked now and send event later
    storeLastBadgeClicked()
      .subscribe(() => sendMessage(new UpdateBadgeAction()));

    // Listen to Show modal event on status report
    listenTo<StatusReportAction>(ACTION.STATUS_REPORT)
      .pipe(
        takeUntil(this.onDestroy$),
      )
      .subscribe(({action}) => {
        this.setModal(action.status);
      });
  }

  setModal(modal: string = null) {
    this.setState({modal});
  }

  render() {
    return <div>
      <UserSettings/>
      <DoneModal show={'DONE' === this.state.modal} onHide={() => this.setModal()}/>
      <ChangeLanguageModal show={'NOT_SUPPORTED_LANGUAGE' === this.state.modal} onHide={() => this.setModal()}/>
      <NoTokenDetectedModal show={'NO_TOKEN_DETECTED' === this.state.modal} onHide={() => this.setModal()}/>
    </div>;
  }
}
