// src/components/done.modal.vue
<template>
  <b-modal
      size="sm"
      centered
      id="DONE"
      :title="'DONE_TITLE' | translatePipe"
  >
    <p v-translate="'DONE_DESCRIPTION'"></p>

    <template #modal-footer="{ok}">
      <leave-feedback-button/>
      <b-button size="sm" variant="success" @click="ok()"> OK</b-button>
    </template>
  </b-modal>
</template>

<script lang="ts">
import {
  BButton,
  BModal,
} from 'bootstrap-vue';
import Vue from 'vue';
import Component from 'vue-class-component';
import link from '../directives/link';
import translate from '../directives/translate';
import translatePipe from '../filters/translate';
import LeaveFeedbackButton from './leave-feedback.button.vue';

@Component({
  name: 'done-modal',
  components: {
    LeaveFeedbackButton,
    BModal,
    BButton,
  },
  filters: {
    translatePipe,
  },
  directives: {
    translate,
    link,
  },
})
export default class DoneModal extends Vue {
  // @TODO ADD DESCRIPTION REGARDING OUTLOOK EVENTS REMOVAL ISSUES
}
</script>

// src/components/modals/done.modal.tsx
import React from 'react';
import {
  Button,
  Modal,
  ModalProps,
} from 'react-bootstrap';
import { translate } from '../../filters/translate';

export default class DoneModal extends React.Component<ModalProps, any> {
  // @TODO ADD DESCRIPTION REGARDING OUTLOOK EVENTS REMOVAL ISSUES
  render() {
    return <Modal
      size='sm'
      centered
      id='DONE'
    >
      <Modal.Header>
        {translate('DONE_TITLE')}
      </Modal.Header>
      <Modal.Body>
        <p>{translate('DONE_DESCRIPTION')}</p>
      </Modal.Body>

      <Modal.Footer>
        {/*<leave-feedback-button/>*/}
        <Button
          variant='success'
          size='sm'
          onClick={this.props.onHide}
        > Ok</Button>
      </Modal.Footer>
    </Modal>;
  }
}
