// src/components/buy-coffee.button.vue
<template>
  <b-button size="sm" variant="outline-dark"
            v-link.close.active="'BUY_ME_COFFEE_LINK'"
            :inner-html.prop="'BUY_ME_COFFEE_TITLE' | translatePipe"></b-button>
</template>

<script lang="ts">
import { BButton } from 'bootstrap-vue';
import Vue from 'vue';
import Component from 'vue-class-component';
import link from '../directives/link';
import translateFilter from '../filters/translate';

@Component({
  name: 'buy-coffee-button',
  components: {
    'b-button': BButton,
  },
  directives: {
    link,
  },
  filters: {
    translatePipe: translateFilter,
  },
})
export default class BuyCoffeeButton extends Vue {
}
</script>

// src/components/buy-coffee.button/buy-coffee.button.tsx
import { Button } from '@material-ui/core';
import React, { FunctionComponent } from 'react';
import handleLink from '../../filters/handleLink';
import { translate } from '../../filters/translate';

const BuyCoffeeButton: FunctionComponent = () => {
  return (
    <Button
      onClick={(e) => handleLink(e, 'BUY_ME_COFFEE_LINK', {close: true, active: true})}
    >
      {translate('BUY_ME_COFFEE_TITLE')}
    </Button>
  );
};

export default BuyCoffeeButton;
