// src/components/modals/change-language.modal.tsx
import React from 'react';
import {
  Button,
  Modal,
  ModalProps,
} from 'react-bootstrap';
import translateFilter from '../../filters/translate';
import { getLanguagesList } from '../../libs/lib';

export default class ChangeLanguageModal extends React.Component<ModalProps, any> {
  languages = getLanguagesList().map(e => `<span class="badge badge-info">${e}</span>`).join(' ');

  render() {
    return <Modal.Dialog
      size='sm'
      centered
      id='NOT_SUPPORTED_LANGUAGE'
    >
      <Modal.Header>
        {translateFilter('NOT_SUPPORTED_LANGUAGE', this.languages)}
      </Modal.Header>
      <Modal.Body>
        <p>{translateFilter('NO_TOKEN_DETECTED')}</p>
      </Modal.Body>

      <Modal.Footer>
        <Button
          size='sm'
          className='ml-auto'
          variant='primary'
          // v-link.close.active="'CHANGE_FACEBOOK_LANGUAGE_LINK'"
        >{translateFilter('CHANGE_FACEBOOK_LANGUAGE_LINK_TITLE')}</Button>

        <Button size='sm' onClick={this.props.onHide}> Close</Button>
      </Modal.Footer>
    </Modal.Dialog>;
  }
}

// src/components/change-language.modal.vue
<template>
  <b-modal
      size="sm"
      centered
      id="NOT_SUPPORTED_LANGUAGE"
      :title="'NOT_SUPPORTED_LANGUAGE_TITLE' | translatePipe"
  >
    <p v-translate="['NOT_SUPPORTED_LANGUAGE', languages]"></p>

    <template #modal-footer="{cancel}">
      <b-button
          size="sm"
          class="ml-auto"
          variant="success"
          v-link.close.active="'CHANGE_FACEBOOK_LANGUAGE_LINK'"
          v-translate="'CHANGE_FACEBOOK_LANGUAGE_LINK_TITLE'"></b-button>

      <b-button size="sm" @click="cancel()"> Close</b-button>
    </template>
  </b-modal>
</template>

<script lang="ts">
import {
  BButton,
  BModal,
  BBadge,
} from 'bootstrap-vue';
import Vue from 'vue';
import Component from 'vue-class-component';
import link from '../directives/link';
import translate from '../directives/translate';
import translateFilter from '../filters/translate';
import { getLanguagesList } from '../libs/lib';

@Component({
  name: 'change-language-modal',
  components: {
    BModal,
    BButton,
    BBadge,
  },
  filters: {
    translatePipe: translateFilter,
  },
  directives: {
    translate,
    link,
  },
})
export default class ChangeLanguageModal extends Vue {
  languages = getLanguagesList().map(e => `<span class="badge badge-info">${e}</span>`).join(' ');
}
</script>
