// src/components/leave-feedback.button.vue
<template>
  <b-button
      size="sm"
      class="ml-auto"
      variant="outline-dark"
      v-link.close.active="'LEAVE_FEEDBACK_LINK'"
      v-translate="'LEAVE_FEEDBACK_TITLE'"></b-button>
</template>

<script lang="ts">
import { BButton } from 'bootstrap-vue';
import Vue from 'vue';
import Component from 'vue-class-component';
import link from '../directives/link';
import translate from '../directives/translate';

@Component({
  name: 'leave-feedback-button',
  components: {
    'b-button': BButton,
  },
  directives: {
    link,
    translate,
  },
})
export default class LeaveFeedbackButton extends Vue {
}
</script>

// src/components/leave-feedback.button.tsx
import React from 'react';
import { Button } from 'react-bootstrap';
import translate from '../filters/translate';

export default class LeaveFeedbackButton extends React.Component<any, any> {
  render() {
    return <Button
      size='sm'
      className='ml-auto'
      variant='outline-dark'
      // v-link.close.active=''LEAVE_FEEDBACK_LINK''
    >
      {translate('LEAVE_FEEDBACK_TITLE')}
    </Button>;
  }
}
