// src/components/modals/no-token-detected.modal.tsx
import React from 'react';
import {
  Button,
  Modal,
  ModalProps,
} from 'react-bootstrap';

import translateFilter from '../../filters/translate';

export default class NoTokenDetectedModal extends React.Component<ModalProps, any> {
  render() {
    return <Modal.Dialog
      size='sm'
      centered
      id='NO_TOKEN_DETECTED'
    >
      <Modal.Header>
        {translateFilter('ERROR_HEADER')}
      </Modal.Header>
      <Modal.Body>
        <p>{translateFilter('NO_TOKEN_DETECTED')}</p>
      </Modal.Body>

      <Modal.Footer>
        <Button
          size='sm'
          className='ml-auto'
          variant='primary'
        >{translateFilter('LOG_INTO_FACEBOOK_TITLE')}</Button>

        <Button size='sm' onClick={this.props.onHide}> Close</Button>
      </Modal.Footer>
    </Modal.Dialog>;
  }
}

// src/components/no-token-detected.modal.vue
<template>
  <b-modal
      size="sm"
      centered
      id="NO_TOKEN_DETECTED"
      :title="'ERROR_HEADER' | translatePipe"
  >
    <p v-translate="'NO_TOKEN_DETECTED'"></p>

    <template #modal-footer="{cancel}">
      <b-button
          size="sm"
          class="ml-auto"
          variant="primary"
          v-link.close.active="'LOG_INTO_FACEBOOK_URL'"
          v-translate="'LOG_INTO_FACEBOOK_TITLE'"></b-button>

      <b-button size="sm" @click="cancel()"> Close</b-button>
    </template>
  </b-modal>
</template>

<script lang="ts">
import {
  BButton,
  BModal,
} from 'bootstrap-vue';
import Vue from 'vue';
import Component from 'vue-class-component';
import link from '../directives/link';
import translate from '../directives/translate';
import translateFilter from '../filters/translate';

@Component({
  name: 'no-token-detected-modal',
  components: {
    BModal,
    BButton,
  },
  filters: {
    translatePipe: translateFilter,
  },
  directives: {
    translate,
    link,
  },
})
export default class NoTokenDetectedModal extends Vue {

}
</script>
