// src/components/toolz.tsx
import {
  ListGroup,
  ListGroupItem,
} from 'react-bootstrap';
import React from 'react';
import {
  setBadgeColor,
  setBadgeText,
} from '../libs/badge';
import { clearStorage } from '../libs/storage/chrome.storage';

export default class Toolz extends React.Component<any, any> {
  clearChromeStorage() {
    clearStorage();
  }

  clearBadge() {
    setBadgeText('');
    setBadgeColor();
  }

  render() {
    return <ListGroup>
      <ListGroupItem onClick={this.clearChromeStorage}>Clear Chrome Local Storage</ListGroupItem>
      <ListGroupItem onClick={this.clearBadge}>Clear Badge</ListGroupItem>
    </ListGroup>;
  }
}

// src/components/toolz.vue
<template>
  <b-list-group>
    <b-list-group-item @click="clearChromeStorage">Clear Chrome Local Storage</b-list-group-item>
    <b-list-group-item @click="clearBadge">Clear Badge</b-list-group-item>
  </b-list-group>
</template>

<script lang="ts">
import {
  BButton,
  BListGroup,
  BListGroupItem,
} from 'bootstrap-vue';
import Vue from 'vue';
import Component from 'vue-class-component';
import {
  setBadgeColor,
  setBadgeText,
} from '../libs/badge';
import { clearStorage } from '../libs/storage/chrome.storage';

@Component({
  name: 'toolz',
  components: {
    BListGroup,
    BListGroupItem,
    BButton,
  },
})
export default class ToolzComponent extends Vue {
  clearChromeStorage(){
    clearStorage();
  }
  clearBadge(){
    setBadgeText('');
    setBadgeColor();
  }
}
</script>
